### ISSUE TITLE
transformCatCov how-to-use for a covariate with three-categories

### ISSUE THREAD

**Issue by koversz** [iame-researchCenter/saemix#1]
Dear Dr Comets,

I would like to ask how to use saemix::transformCatCov() for a covariate with three-categories. My aim is to build a pharmacokinetic model with this covariate affecting the pharmacokinetic  parameter ka.
I could not understand the description of the group argument of transformCatCov(). It seems that without transforming the three-categories covariate, the saemix model gives only one "beta" estimating the effect of this covariate on parameter ka, as it was a two-categories covariate. Leaving the group argument empty did not work.
Could you please provide an example for a three-categories covariate with levels "A", "B" and "C"?

Thanks a lot for your effort,

Szilvia Kövér
kover.szilvia@univet.hu
University of Veterinary Medicine Budapest
Department of Zoology

**Comment by ecomets** [comment]
#### Here is an example (using the cow.saemix dataset in the package):

library(saemix)

data(cow.saemix)
saemix.data<-saemixData(name.data=cow.saemix,header=TRUE,name.group=c("cow"), 
      name.predictors=c("time"),name.response=c("weight"), 
      name.covariates=c("birthyear","twin","birthrank"), 
      units=list(x="days",y="kg",covariates=c("yr","-","-")))
unique(saemix.data@data$birthrank) # 5 categories, 3 4 5 6 7

cowt <- transformCatCov(saemix.data, covariate=birthrank, group=c(1,2,2,3,3), verbose=T)   # create 2 dummy variables regrouping 4 and 5, and 6 and 7

head(saemix.data@data) # the original covariate is birthrank
head(cowt@data)   # the new covariates are birthrank.G2 (regrouping 4 and 5) and birthrank.G3 (6 and 7)

#### you can check the repartition by
table(saemix.data@data$birthrank)
table(cowt@data$birthrank.G2)
table(cowt@data$birthrank.G3)

#### you can also change the reference class, for example to group 2
cowt <- transformCatCov(saemix.data, covariate=birthrank, group=c(1,2,2,3,3), reference=2, verbose=T)
head(cowt@data)   # the new covariates are birthrank.G2 (1) and birthrank.G3 (6 and 7)


#### then you can run the analysis by using both birthrank.G2 and birthrank.G3 as covariates, and estimate the corresponding betas.
